config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

# Local Login/Signup Routes
get '/signup' => 'users#new_signup'                 # Local Sign Up Form
post '/signup' => 'users#create_signup'             # Local Signup Post Path
get '/login' => 'users#new_login'                   # Log In Form
post '/login' => 'users#create_login'               # Log In Post Path (NOTE: same route as Facebook login)
post '/logout' => 'users#destroy'                   # Log Out

# Facebook Login/Signup Routes
get '/auth/facebook/callback' => 'facebook#create'  # Sign in from Facebook
get '/fb_login' => 'facebook#dont_refresh'          # Cannot refresh Facebook Username Selection page
post '/fb_login' => 'facebook#username'             # Setup username after Facebook sign in

# Penpal and Letter Routes
# Nested
resources :penpals, only: [:index, :show, :new, :create] do
 resources :letters, only: [:index, :show, :new, :create]
end
# Not Nested
get '/letters' => 'letters#index'

end

app/models/penpal.rb
class Penpal < ApplicationRecord
validates_presence_of :name
validates_numericality_of :age, :message => "required and must be a number"
validate :has_one_or_more_interests

has_many :letters
has_many :users, through: :letters
has_many :penpal_interests
has_many :interests, through: :penpal_interests

# Validations

def has_one_or_more_interests
 if interests.empty?
 errors.add(:interest_ids, "required. Must select one interest.")
 end
end

# Scope Methods

scope :alphabetically, -> { order(first_name: :asc) }
scope :by_interest, -> (int_id) { joins(:interests).where(interests: {id: int_id}) }
scope :by_frequency, -> (freq) { where(frequency: freq) }
scope :by_penpal, -> (penpal_id) { where(id: penpal_id) }
scope :by_created, -> { order(created_at: :asc) }

# Instance Methods

def display_interests
 interests.collect {|interest| interest.name }.join(", ")
end

def letters_from_me(me)
 letters.where(user: me)
end

def name
 first_name+" "+last_name
end

end

app/controllers/penpals_controller.rb
class PenpalsController < ApplicationController
    before_action :must_be_logged_in
    helper_method :check_for_params, :penpals?

    def index
     if !params[:interest].blank? && !params[:frequency].blank?
      @penpals = Penpal.by_interest(params[:interest]).by_frequency(params[:frequency]).alphabetically
     elsif !params[:interest].blank?
      @penpals = Penpal.by_interest(params[:interest]).alphabetically
     elsif !params[:frequency].blank?
      @penpals = Penpal.by_frequency(params[:frequency]).alphabetically
     else
      @penpals = Penpal.alphabetically
     end
    end

    def show
     flash[:error] = nil
     @penpal = Penpal.find(params[:id])
     @letters = @penpal.letters_from_me(current_user)
    end

    def new
     @penpal = Penpal.new
    end

    def create
    @penpal = Penpal.new(penpal_params)
     if @penpal.save
      redirect_to @penpal
     else
      flash_errors(@penpal)
      render :new
     end
    end

    private

    def penpal_params
    params.require(:penpal).permit(:first_name, :last_name, :age, :frequency, interest_ids:[])
    end

    # Helper Methods

    def check_for_params
     !params[:interest].blank? || !params[:frequency].blank?
    end

    def penpals?(penpal)
     penpal.users.include?(current_user)
    end
    
end

app/views/penpals/index.html.erb
<p>This page shows all penpals registered on the Web site. Use the filter to narrow down your 
search by interest and/or letter frequency (which is how often a penpal wants to receive letters from you).</p>

<p>Penpals you have written letters to before are highlighted with an asterisk *</p>

<%= form_tag("/penpals", method: "get") do %>
  <%= select_tag "interest", options_from_collection_for_select(Interest.all, "id", "name", params[:interest]), include_blank: "Interest" %>
  <%= select_tag "frequency", options_for_select(['Weekly', 'Monthly', 'Yearly'], params[:frequency]), include_blank: "Frequency" %>
  <%= submit_tag "Filter" %>
<% end %>

<% unless @penpals.empty? %>
  <ul>
  <% @penpals.each do |penpal| %>
  <li> <%= link_to penpal.name, penpal %> <%= "*" if penpals?(penpal) %> </li>
  <% end %>
  </ul>
<% else %>
  <% if Penpal.all.empty? %>
  <p>There are no registered penpals.</p>
  <% else %>
  <p>No registered penpals meet the provided search criteria.</p>
  <% end %>
<% end %>

<% if check_for_params %>
<%= form_for "/penpals", method: "get" do |f| %>
  <%= f.submit "Reset Filter" %>
<% end %><% end %>
<br />

<%= link_to "Register New Penpal", new_penpal_url, class: "button" %>

app/views/penpals/new.html.erb
<p> New penpal registration </p>

<%= form_for @penpal do |f| %>

    <%= f.label :first_name %>:
    <%= f.text_field :first_name %><br />
    <%= f.label :last_name %>:
    <%= f.text_field :last_name %><br />
    <%= f.label :age %>:
    <%= f.text_field :age %><br />

    <%= f.label :frequency, "Frequency you want to receive letters" %>:
    <%= f.collection_select :frequency, ['Weekly', 'Monthly', 'Yearly'], :to_s, :to_s %><br />

    <%= f.label :interest_ids, "Interests (pick at least one)" %>:<br />
    <%= f.collection_check_boxes(:interest_ids, Interest.all, :id, :name) %><br />
    
    <%= f.submit "Register Penpal" %>
<% end %>

app/views/penpals/show.html.erb
<ul>
 <li> Name: <%= @penpal.name %> </li>
 <li> Age: <%= @penpal.age %> </li>
 <li> Frequency: <%= @penpal.frequency %> </li>
 <li> <%= "Interest".pluralize(@penpal.interests.count) %>: <%= @penpal.display_interests %> </li>
 </ul>
 <br />

 <% if !@letters.empty? %>
 <%= link_to "Letters with #{@penpal.first_name}", penpal_letters_url(@penpal), class: "button" %>
 <% end %>
 <%= link_to "Send Letter to #{@penpal.first_name}", new_penpal_letter_url(@penpal), class: "button" %>