config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

# Local Login/Signup Routes
get '/signup' => 'users#new_signup'                 # Local Sign Up Form
post '/signup' => 'users#create_signup'             # Local Signup Post Path
get '/login' => 'users#new_login'                   # Log In Form
post '/login' => 'users#create_login'               # Log In Post Path (NOTE: same route as Facebook login)
post '/logout' => 'users#destroy'                   # Log Out

# Facebook Login/Signup Routes
get '/auth/facebook/callback' => 'facebook#create'  # Sign in from Facebook
get '/fb_login' => 'facebook#dont_refresh'          # Cannot refresh Facebook Username Selection page
post '/fb_login' => 'facebook#username'             # Setup username after Facebook sign in

# Penpal and Letter Routes
# Nested
resources :penpals, only: [:index, :show, :new, :create] do
 resources :letters, only: [:index, :show, :new, :create]
end
# Not Nested
get '/letters' => 'letters#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    flash[:error] = nil
    end
end

app/views/welcome/index.html.erb
<div class="login_box">

<% if logged_in? %>
 
    <% if current_user.penpals.count!=0 %>
      <p>Welcome back, <%= current_user.username %>.</p>
      <p>You have <%= current_user.penpals.uniq.count %> penpals.</p>
    <% else %>
      <p>Welcome to Elder Pals, <%= current_user.username %>.</p>
      <p>To get started, navigate to our <%= link_to "Pen Pals", penpals_url %> section.</p>
    <% end %>

<% else %>

    <p>Welcome to Elder Pals, the best way to meet and connect with new friends from another generation.</p>
    <p>Our Web site rekindles the concept of penpals for the modern world.</p>
    <p> <%= link_to "Sign Up", '/signup' %> / <%= link_to "Log In", '/login' %> </p>

<% end %>

</div>