config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

# Local Login/Signup Routes
get '/signup' => 'users#new_signup'                 # Local Sign Up Form
post '/signup' => 'users#create_signup'             # Local Signup Post Path
get '/login' => 'users#new_login'                   # Log In Form
post '/login' => 'users#create_login'               # Log In Post Path (NOTE: same route as Facebook login)
post '/logout' => 'users#destroy'                   # Log Out

# Facebook Login/Signup Routes
get '/auth/facebook/callback' => 'facebook#create'  # Sign in from Facebook
get '/fb_login' => 'facebook#dont_refresh'          # Cannot refresh Facebook Username Selection page
post '/fb_login' => 'facebook#username'             # Setup username after Facebook sign in

# Penpal and Letter Routes
# Nested
resources :penpals, only: [:index, :show, :new, :create] do
 resources :letters, only: [:index, :show, :new, :create]
end
# Not Nested
get '/letters' => 'letters#index'

end

app/models/letter.rb
class Letter < ApplicationRecord
validates_presence_of :title, :message
belongs_to :user
belongs_to :penpal
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
    before_action :confirm_user, only: [:show]
    before_action :must_be_logged_in

    def index
      if params.include?(:penpal_id)
       @penpals = current_user.penpals.by_penpal(params[:penpal_id]).uniq
       @index_message = "letters sent to #{Penpal.find(params[:penpal_id]).first_name}."
       @empty_message = "You have not sent any letters to #{Penpal.find(params[:penpal_id]).first_name}."
      else
       @penpals = current_user.penpals.uniq
       @index_message = "all letters."
       @empty_message = "You have not sent any letters."
      end
    end

    def show
     flash[:error] = nil
     @penpal = Penpal.find(params[:penpal_id])
     @letter = Letter.find(params[:id])
    end

    def new
     @letter = Letter.new
     @penpal = Penpal.find(params[:penpal_id])
    end

    def create
     @letter = Letter.new(letter_params)
     if @letter.save
      redirect_to penpal_letter_url(@letter.penpal, @letter)
     else
      flash_errors(@letter)
      @penpal = @letter.penpal
      render :new
     end
    end

    private

    def confirm_user
     return head(:forbidden) unless Letter.find(params[:id]).user == current_user
    end

    def letter_params
      params.require(:letter).permit(:title, :message, :user_id, :penpal_id)
    end
end

app/views/letters/index.html.erb
<% unless @penpals.empty? %>

<p> Currently viewing: <%= @index_message %> </p>
<table>
  <% @penpals.each do |penpal| %>
  <tr><td id="t_penpal"> Letters sent to <%= link_to penpal.first_name, penpal_letters_url(penpal) %>:</td></tr>
    <% letters = penpal.letters.where(user: current_user) %>
    <% letters.each do |letter| %>
    <tr> <td id="t_letter"> <%= link_to "● "+letter.title, penpal_letter_url(penpal, letter) %> </td></tr>
    <% end %>
  <% end %>
</table>

<% else %>
  <p> <%= @empty_message %> </p>
<% end %>

app/views/letters/new.html.erb
<p> Create a new leter for <%= @penpal.first_name %>:</p>

<%= form_for @letter, url: penpal_letters_path(@penpal.id) do |f| %>
    <%= f.hidden_field :penpal_id, :value => @penpal.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.label :title, "Greeting" %>:
    <%= f.text_field :title %><br />
    <%= f.label :message %>:
    <%= f.text_area :message %><br />
    
    <%= f.submit "Send Letter" %>
<% end %>

app/views/letters/show.html.erb
<p>The following letter has been delivered to <%= @letter.penpal.name %> by Elder Pals:</p>

<div class="letter">
<p class="letter_left"><%= @letter.title %>:</p>
<p><%= @letter.message %></p>
<p class="letter_right"> — From <%= current_user.username %> </p>
</div>